# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Inicio"
  url = "/"
  weight = 10

[[main]]
  name = "Asociación"
  url = "asociacion"
  weight = 11

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 12


[[main]]
  name = "Eventos"
  url = "#talks"
  weight = 13

[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 14


[[main]]
  name = "Inscríbete"
  url = "alta-socios"
  weight = 15

[[main]]
  name = "Libro SIG"
  url = "https://www.lulu.com/es/shop/victor-olaya-ferrero/sistemas-de-informaci%C3%B3n-geogr%C3%A1fica/hardcover/product-76em9n.html"
  weight = 16

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
